name: flutter_001
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.20 # goi sang app khac: sms, call, email.
  flutter_svg: ^1.0.3
  lottie: ^1.2.2
  font_awesome_flutter: ^9.2.0
  persistent_bottom_nav_bar: ^4.0.2
  webview_flutter: ^3.0.1       #  webview not ios

  # transparent_image: "^0.1.0"
  # cached_network_image: "^0.4.1"
  # query_params: "^0.5.0"

  # sqflite: ^1.1.6+1

  # flutter_bloc: ^8.0.1
  http: ^0.13.4
  equatable: ^2.0.0
  # flutter_bloc: ^4.0.0
  # scoped_model: ^1.0.1
  # provider: ^3.1.0+1
  # flutter_lorem: ^1.1.0
  # redux: ^3.0.0
  # flutter_redux: ^0.5.3
  flutter_bloc:
    path: packages/flutter_bloc
  flutter_services_binding: ^0.1.0
  google_fonts: ^2.1.0
  hydrated_bloc:
    path: packages/hydrated_bloc
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  weather_repository:
    path: packages/weather_repository

dependency_overrides:
  bloc:
    path: packages/bloc
  flutter_bloc:
    path: packages/flutter_bloc
  hydrated_bloc:
    path: packages/hydrated_bloc
  bloc_test:
    path: packages/bloc_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test:
    path: packages/bloc_test
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
